---
version: "3"
services:
 devopsdb:
   image: kavyacherukuru/myapp:db
   ports:
     - "3306:3306"

 application:
   image: kavyacherukuru/myapp:app
   ports:
     - "1234:8080"
   depends_on:
     - "devopsdb"
